name: Integración Continua GEE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install earthengine-api folium google-auth
        
    - name: Autenticación con Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    - name: Ejecutar Script de Earth Engine
      run: |
        python main.py
        echo "¡El código se ejecutó en la nube correctamente!"

    # --- MOVEMOS EL MAPA A UNA CARPETA AISLADA Y SEGURA ---
    - name: Preparar carpeta pública
      run: |
        mkdir public
        mv mapa_finca.html public/

    # --- PUBLICAMOS SOLO ESA CARPETA ---
    - name: Publicar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages